application: rowanc1
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: static/images
- url: /html
  static_dir: static/html
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /pdf
  static_dir: static/pdf

- url: .*
  script: server.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: PIL
  version: "1.1.7"
- name: numpy
  version: "1.6.1"
- name: jinja2
  version: latest
